// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ddp-server/internal/service/internal/dao/internal"
)

// demoGenDao is the data access object for table demo_gen.
// You can define custom methods on it to extend its functionality as you wish.
type demoGenDao struct {
	*internal.DemoGenDao
}

var (
	// DemoGen is globally public accessible object for table demo_gen operations.
	DemoGen = demoGenDao{
		internal.NewDemoGenDao(),
	}
)

// Fill with you ideas below.
