// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ddp-server/internal/service/internal/dao/internal"
)

// demoGenTreeDao is the data access object for table demo_gen_tree.
// You can define custom methods on it to extend its functionality as you wish.
type demoGenTreeDao struct {
	*internal.DemoGenTreeDao
}

var (
	// DemoGenTree is globally public accessible object for table demo_gen_tree operations.
	DemoGenTree = demoGenTreeDao{
		internal.NewDemoGenTreeDao(),
	}
)

// Fill with you ideas below.
