// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ddp-server/internal/service/internal/dao/internal"
)

// sysModelInfoDao is the data access object for table sys_model_info.
// You can define custom methods on it to extend its functionality as you wish.
type sysModelInfoDao struct {
	*internal.SysModelInfoDao
}

var (
	// SysModelInfo is globally public accessible object for table sys_model_info operations.
	SysModelInfo = sysModelInfoDao{
		internal.NewSysModelInfoDao(),
	}
)

// Fill with you ideas below.
