// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ddp-server/internal/service/internal/dao/internal"
)

// toolsGenTableDao is the data access object for table tools_gen_table.
// You can define custom methods on it to extend its functionality as you wish.
type toolsGenTableDao struct {
	*internal.ToolsGenTableDao
}

var (
	// ToolsGenTable is globally public accessible object for table tools_gen_table operations.
	ToolsGenTable = toolsGenTableDao{
		internal.NewToolsGenTableDao(),
	}
)

// Fill with you ideas below.
