// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-17 18:44:17
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// DemoGenTree is the golang structure of table demo_gen_tree for DAO operations like Where/Data.
type DemoGenTree struct {
	g.Meta     `orm:"table:demo_gen_tree, do:true"`
	Id         interface{} //
	ParentId   interface{} // 父级ID
	DemoName   interface{} // 姓名
	DemoAge    interface{} // 年龄
	Classes    interface{} // 班级
	DemoBorn   *gtime.Time // 出生年月
	DemoGender interface{} // 性别
	CreatedAt  *gtime.Time // 创建日期
	UpdatedAt  *gtime.Time // 修改日期
	DeletedAt  *gtime.Time // 删除日期
	CreatedBy  interface{} // 创建人
	UpdatedBy  interface{} // 修改人
	DemoStatus interface{} // 状态
	DemoCate   interface{} // 分类
}
