// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-17 19:13:28
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Order is the golang structure of table gf_order for DAO operations like Where/Data.
type Order struct {
	g.Meta     `orm:"table:gf_order, do:true"`
	Id         interface{} // 自增ID
	CategoryId interface{} // 外键
}
