// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-17 18:44:17
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// PluginsManage is the golang structure of table plugins_manage for DAO operations like Where/Data.
type PluginsManage struct {
	g.Meta        `orm:"table:plugins_manage, do:true"`
	Id            interface{} // ID
	StoreId       interface{} // 插件在商城中的id
	PName         interface{} // 插件名称英文
	PTitle        interface{} // 插件名称
	PDescription  interface{} // 插件介绍
	PAuth         interface{} // 作者
	IsInstall     interface{} // 是否安装
	Status        interface{} // 状态
	Version       interface{} // 当前版本
	Price         interface{} // 价格
	DownloadTimes interface{} // 下载次数
	InstallPath   interface{} // 安装路径（用于卸载）
}
