// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-17 18:44:17
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SysModelInfo is the golang structure of table sys_model_info for DAO operations like Where/Data.
type SysModelInfo struct {
	g.Meta          `orm:"table:sys_model_info, do:true"`
	ModelId         interface{} // 模型ID
	ModelCategoryId interface{} // 模板分类id
	ModelName       interface{} // 模型标识
	ModelTitle      interface{} // 模型名称
	ModelPk         interface{} // 主键字段
	ModelOrder      interface{} // 默认排序字段
	ModelSort       interface{} // 表单字段排序
	ModelList       interface{} // 列表显示字段，为空显示全部
	ModelEdit       interface{} // 可编辑字段，为空则除主键外均可以编辑
	ModelIndexes    interface{} // 索引字段
	SearchList      interface{} // 高级搜索的字段
	CreateTime      interface{} // 创建时间
	UpdateTime      interface{} // 更新时间
	ModelStatus     interface{} // 状态
	ModelEngine     interface{} // 数据库引擎
	CreateBy        interface{} // 创建人
	UpdateBy        interface{} // 修改人
}
