// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-17 18:44:17
// =================================================================================

package entity

// DemoGenClass is the golang structure for table demo_gen_class.
type DemoGenClass struct {
	Id        uint   `json:"id"        description:"分类id"`
	ClassName string `json:"className" description:"分类名"`
}
