// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-17 19:13:28
// =================================================================================

package entity

// Order is the golang structure for table order.
type Order struct {
	Id         uint `json:"id"         description:"自增ID"`
	CategoryId uint `json:"categoryId" description:"外键"`
}
