// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-17 18:44:17
// =================================================================================

package entity

// PluginsManage is the golang structure for table plugins_manage.
type PluginsManage struct {
	Id            uint   `json:"id"            description:"ID"`
	StoreId       int    `json:"storeId"       description:"插件在商城中的id"`
	PName         string `json:"pName"         description:"插件名称英文"`
	PTitle        string `json:"pTitle"        description:"插件名称"`
	PDescription  string `json:"pDescription"  description:"插件介绍"`
	PAuth         string `json:"pAuth"         description:"作者"`
	IsInstall     int    `json:"isInstall"     description:"是否安装"`
	Status        int    `json:"status"        description:"状态"`
	Version       string `json:"version"       description:"当前版本"`
	Price         uint   `json:"price"         description:"价格"`
	DownloadTimes uint   `json:"downloadTimes" description:"下载次数"`
	InstallPath   string `json:"installPath"   description:"安装路径（用于卸载）"`
}
