// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-17 18:44:17
// =================================================================================

package entity

// SysModelInfo is the golang structure for table sys_model_info.
type SysModelInfo struct {
	ModelId         uint   `json:"modelId"         description:"模型ID"`
	ModelCategoryId uint   `json:"modelCategoryId" description:"模板分类id"`
	ModelName       string `json:"modelName"       description:"模型标识"`
	ModelTitle      string `json:"modelTitle"      description:"模型名称"`
	ModelPk         string `json:"modelPk"         description:"主键字段"`
	ModelOrder      string `json:"modelOrder"      description:"默认排序字段"`
	ModelSort       string `json:"modelSort"       description:"表单字段排序"`
	ModelList       string `json:"modelList"       description:"列表显示字段，为空显示全部"`
	ModelEdit       string `json:"modelEdit"       description:"可编辑字段，为空则除主键外均可以编辑"`
	ModelIndexes    string `json:"modelIndexes"    description:"索引字段"`
	SearchList      string `json:"searchList"      description:"高级搜索的字段"`
	CreateTime      uint64 `json:"createTime"      description:"创建时间"`
	UpdateTime      uint64 `json:"updateTime"      description:"更新时间"`
	ModelStatus     uint   `json:"modelStatus"     description:"状态"`
	ModelEngine     string `json:"modelEngine"     description:"数据库引擎"`
	CreateBy        uint64 `json:"createBy"        description:"创建人"`
	UpdateBy        uint64 `json:"updateBy"        description:"修改人"`
}
