// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-17 18:44:17
// =================================================================================

package entity

// SysWebSet is the golang structure for table sys_web_set.
type SysWebSet struct {
	WebId      int    `json:"webId"      description:"主键"`
	WebContent string `json:"webContent" description:"站点信息"`
}
