// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-17 18:44:17
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysWebSetDao is the data access object for table sys_web_set.
type SysWebSetDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns SysWebSetColumns // columns contains all the column names of Table for convenient usage.
}

// SysWebSetColumns defines and stores column names for table sys_web_set.
type SysWebSetColumns struct {
	WebId      string // 主键
	WebContent string // 站点信息
}

//  sysWebSetColumns holds the columns for table sys_web_set.
var sysWebSetColumns = SysWebSetColumns{
	WebId:      "web_id",
	WebContent: "web_content",
}

// NewSysWebSetDao creates and returns a new DAO object for table data access.
func NewSysWebSetDao() *SysWebSetDao {
	return &SysWebSetDao{
		group:   "default",
		table:   "sys_web_set",
		columns: sysWebSetColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysWebSetDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysWebSetDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SysWebSetDao) Columns() SysWebSetColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SysWebSetDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysWebSetDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysWebSetDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
